/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Tue Jan 19 10:32:59 2010
  */


/*
 * Include Files
 *
 */
#include "simstruc.h"


/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void DAQCountsToEU_Outputs_wrapper(const uint32_T *u0,
                          real_T *y0  , 
                          const real_T  *gain, const int_T  p_width0, 
                          const real_T  *Vslope, const int_T  p_width1, 
                          const real_T  *Voffset, const int_T  p_width2, 
                          const real_T  *EUslope, const int_T  p_width3, 
                          const real_T  *EUoffset,  const int_T p_width4,
			     const int_T y_width, const int_T u_width, SimStruct *S)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
int i = 0;
int_T numElements = u_width;
for (i = 0; i < numElements; i++) {
  int val;
  val = u0[i]/65536;
  
  if (val > 0x7FFF)
     val = -((val ^ 0xFFFF) + 1);
  
  y0[i] = ((((((10000.0 / gain[0])/32768.0) * val) * Vslope[0]) + Voffset[0]) * EUslope[0]) + EUoffset[0];
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
