%% This program gathers all the SCRAMNet memory and DAQ channels and writes
%  to a CSV File

clear;
clc;
close all;

%% Create a SCRAMNet Object
scr = edu.lehigh.nees.scramnet.ScramNetIO;
scr.initScramnet; 

%% SCRAMNet memory mapping
disp1_acmd_in_scr = 1;          % Disp 1 Actuator Command
disp1_cmd_in_scr = 2;           % Disp 1 Relative Command
disp1_in_scr = 3;               % Disp 1 
disp1_in_off_scr = 4;           % Disp 1 offset
load1_k_scr = 5;                % Load 1

disp2_acmd_in_scr = 8;          % Disp 2 Actuator Command
disp2_cmd_in_scr = 9;           % Disp 2 Relative Command
disp2_in_scr = 10;              % Disp 2 
disp2_in_off_scr = 11;          % Disp 2 offset
load2_k_scr = 12;               % Load 2

disp3_acmd_in_scr = 16;         % Disp 3 Actuator Command
disp3_cmd_in_scr = 17;          % Disp 3 Relative Command
disp3_in_scr = 18;              % Disp 3 
disp3_in_off_scr = 19;          % Disp 3 offset
load3_k_scr = 20;               % Load 3

disp4_acmd_in_scr = 24;         % Disp 4 Actuator Command
disp4_cmd_in_scr = 25;          % Disp 4 Relative Command
disp4_in_scr = 26;              % Disp 4 
disp4_in_off_scr = 27;          % Disp 4 offset
load4_k_scr = 28;               % Load 4

step_scr = 32;                  % Step
trigger_scr = 61;               % Trigger

F1PT_scr = 2000;                % 1st Floor Post Tensioning
F2PT_scr = 2001;                % 2nd Floor Post Tensioning
F3PT_scr = 2002;                % 3rd Floor Post Tensioning
F4PT_scr = 2003;                % 4th Floor Post Tensioning
F1Drift_scr = 2004;             % 1st Floor Drift
F2Drift_scr = 2005;             % 2nd Floor Drift
F3Drift_scr = 2006;             % 3rd Floor Drift
F4Drift_scr = 2007;             % 4th Floor Drift
F1StoryShear_scr = 2008;        % 1st Floor Story Shear
F2StoryShear_scr = 2009;        % 2nd Floor Story Shear
F3StoryShear_scr = 2010;        % 3rd Floor Story Shear
F4StoryShear_scr = 2011;        % 4th Floor Story Shear

%% Read in DAQ configuration
daqfile = [pwd '\daq config\daq.xml'];
daqxmlfile = java.io.File(daqfile);                 %Open the DAQ XML config file
daqxml = edu.lehigh.nees.xml.ReadDAQXMLConfig(daqxmlfile); %Parse the DAQ XML file
daq = daqxml.getDAQConfig;                              %Save the configuration
numdaqchannels = daq.getnumDaqBlocks;           %Get number of daq channels
% Get the channel configuration 
for d = 0 : numdaqchannels-1
    daqchannelinfo.name(d+1) = daq.getDaqName(d);
    daqchannelinfo.offset(d+1) = daq.getDaqOffset(d);
    daqchannelinfo.gain(d+1) = daq.getDaqGain(d);
    daqchannelinfo.Voffset(d+1) = daq.getDaqVoffset(d);
    daqchannelinfo.Vslope(d+1) = daq.getDaqVslope(d);
    daqchannelinfo.EUoffset(d+1) = daq.getDaqEUoffset(d);
    daqchannelinfo.EUslope(d+1) = daq.getDaqEUslope(d);
end

%% Create CSV Writer to log data
csv = edu.lehigh.nees.util.CSVWriter;
csvFilename = ['results\TriggerDAQ_' datestr(now,'yyyy-mm-dd--HH-MM-SS') '.csv'];
csv.open(csvFilename);
header = {  'Step',...
            'Trigger',...
            'Disp 1 Command (in)',...
            'Disp 1 Actuator Command (in)',...
            'Displacement 1 (in)',...            
            'Displacement 1 Offset (in)',...            
            'Load 1 (kips)',...
            'Disp 2 Command (in)',...
            'Disp 2 Actuator Command (in)',...
            'Displacement 2 (in)',...            
            'Displacement 2 Offset (in)',...            
            'Load 2 (kips)',...
            'Disp 3 Command (in)',...
            'Disp 3 Actuator Command (in)',...
            'Displacement 3 (in)',...            
            'Displacement 3 Offset (in)',...            
            'Load 3 (kips)',...
            'Disp 4 Command (in)',...
            'Disp 4 Actuator Command (in)',...
            'Displacement 4 (in)',...            
            'Displacement 4 Offset (in)',...            
            'Load 4 (kips)',...
            '1FPT_(kips)',...
            '2FPT_(kips)',...
            '3FPT_(kips)',...
            '4FPT_(kips)',...
            '1FDrift (in)',...
            '2FDrift (in)',...
            '3FDrift (in)',...
            '4FDrift (in)',...
            '1FStoryShear (kips)',...
            '2FStoryShear (kips)',...
            '3FStoryShear (kips)',...
            '4FStoryShear (kips)'
            }; 
% Add DAQ signals
for d = 1 : numdaqchannels
    header(end+1) = [daqchannelinfo.name(d)];
end
csv.writeHeader(header);

%% Write data to file
disp('Trigger DAQ Running...');
disp('Hit CTRL-C to stop');
trigger = scr.readInt(trigger_scr);
while (trigger == scr.readInt(trigger_scr)) ;
end
while (true)    
    % Create array of SCRAMNet data
    writeData = [   scr.readFloat(step_scr),...
                    scr.readInt(trigger_scr),...
                    scr.readFloat(disp1_cmd_in_scr),...
                    scr.readFloat(disp1_acmd_in_scr),...
                    scr.readFloat(disp1_in_scr),...
                    scr.readFloat(disp1_in_off_scr),...
                    scr.readFloat(load1_k_scr),...
                    scr.readFloat(disp2_cmd_in_scr),...
                    scr.readFloat(disp2_acmd_in_scr),...
                    scr.readFloat(disp2_in_scr),...
                    scr.readFloat(disp2_in_off_scr),...
                    scr.readFloat(load2_k_scr),...
                    scr.readFloat(disp3_cmd_in_scr),...
                    scr.readFloat(disp3_acmd_in_scr),...
                    scr.readFloat(disp3_in_scr),...
                    scr.readFloat(disp3_in_off_scr),...
                    scr.readFloat(load3_k_scr),...
                    scr.readFloat(disp4_cmd_in_scr),...
                    scr.readFloat(disp4_acmd_in_scr),...
                    scr.readFloat(disp4_in_scr),...
                    scr.readFloat(disp4_in_off_scr),...
                    scr.readFloat(load4_k_scr),...
                    scr.readFloat(F1PT_scr),...
                    scr.readFloat(F2PT_scr),...
                    scr.readFloat(F3PT_scr),...
                    scr.readFloat(F4PT_scr),...
                    scr.readFloat(F1Drift_scr),...
                    scr.readFloat(F2Drift_scr),...
                    scr.readFloat(F3Drift_scr),...
                    scr.readFloat(F4Drift_scr),...
                    scr.readFloat(F1StoryShear_scr),...
                    scr.readFloat(F2StoryShear_scr),...
                    scr.readFloat(F3StoryShear_scr),...
                    scr.readFloat(F4StoryShear_scr)
                ];
     % Add DAQ signals
    for d = 1 : numdaqchannels
        writeData(end+1) = scr.readDAQ(daqchannelinfo.offset(d),...
                                       daqchannelinfo.gain(d),...
                                       daqchannelinfo.Voffset(d),...
                                       daqchannelinfo.Vslope(d),...
                                       daqchannelinfo.EUoffset(d),...
                                       daqchannelinfo.EUslope(d));
    end
    csv.write(writeData);
    
	% Wait for next trigger
    trigger = scr.readInt(trigger_scr);
    while (trigger == scr.readInt(trigger_scr)) 
        pause(0.05);
    end
end