/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_lehigh_nees_scramnet_ScramNetIO */

#ifndef _Included_edu_lehigh_nees_scramnet_ScramNetIO
#define _Included_edu_lehigh_nees_scramnet_ScramNetIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    initScramnet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_initScramnet
  (JNIEnv *, jobject);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    unmapScramnet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_unmapScramnet
  (JNIEnv *, jobject);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    setTransMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_setTransMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    readInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_readInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    readLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_readLong
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    readFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_readFloat
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    readDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_readDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    writeInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_writeInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    writeLong
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_writeLong
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    writeFloat
 * Signature: (IF)I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_writeFloat
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    writeDouble
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_writeDouble
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_clear
  (JNIEnv *, jobject);

/*
 * Class:     edu_lehigh_nees_scramnet_ScramNetIO
 * Method:    readGlobalCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_lehigh_nees_scramnet_ScramNetIO_readGlobalCounter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
